### PR TITLE
update feedreader deps

### PR DESCRIPTION
**Pull request by sammyrulez**
5.x do not work on m1 mac.

tested on my m1 mac

### CODE REVIEW

**Comment by Alyetama** [comment]
#18
#22

**Comment by NicolasCaousGV** [comment]
To anyone who wants to use this lib but can't install, you can force the dependencies to be a specific version this way:

```
python -m pip install "beautifulsoup4==4.9.1"
python -m pip install "dateparser==0.7.6"
python -m pip install "requests==2.24.0"
python -m pip install "feedparser==6.0.8"
python -m pip install --no-deps pygooglenews
```

This should work. (If it doesn't, check if the versions have changed in `pyproject.toml` for some reason)

**Comment by sebix** [comment]
> To anyone who wants to use this lib but can't install, you can force the dependencies to be a specific version this way:

Sticking to old versions is not very wise, especially when it comes to parsing input data. Those libs regularly do security fixes.

**Comment by NicolasCaousGV** [comment]
> > To anyone who wants to use this lib but can't install, you can force the dependencies to be a specific version this way:
> 
> Sticking to old versions is not very wise, especially when it comes to parsing input data. Those libs regularly do security fixes.

Thanks for your preoccupation. Using a not-maintained library is itself not a wise decision. But in my use case, where poor security isn't really a problem with what I'm doing, I just needed to make the library work. Anyway, this is a nice warning to future people.

**Pull request closed without merging**
